Add optional `detectionTool` field to CodeTF ChangeSet
pixee/codemodder-specs pull request #19
Opened 2024-03-07 16:55 UTC by drdavella

This doesn't entirely address #17 but I think it adds a small, required set of fields that we definitely want.

In a subsequent change we can add `findings` which offers details about which findings were remediated and which were not.

We can build upon this as necessary but for now I hope we can come to an agreement on the field names.

2024-03-07 21:04 UTC, gilday approved these changes

2024-03-07 21:04 UTC, gilday commented on codetf.json
> +            "ruleName": "Name of the tool vendor rule that detected the issue", (required)
Consider grouping these inside a new, required `rule` object that we can add to if needed.

2024-03-08 15:15 UTC, nahsra requested changes
I think the default should not be to assume pixee found it. It could just be a bad codemod that failed to include this info

I think we should add `guids` to this so we know which issues this change fixes (could be many)

2024-03-08 15:29 UTC, drdavella commented
Closing since this is superseded by #20 and #21

2024-03-08 15:29 UTC, closed without merging